- src/Templates/ODataT4CodeGenerator.cs
- src/Templates/ODataT4CodeGenerator.ttinclude
- test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTest.cs
- test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTestDescriptors.cs
This is part of code Gen migration to connected service.
This is related to the commit to [https://github.com/OData/odata.net/commit/02d3279d](https://github.com/OData/odata.net/commit/02d3279d)
> Introduce VS version variable instead.

- src/Templates/ODataT4CodeGenerator.cs
- src/Templates/ODataT4CodeGenerator.tt
- src/Templates/ODataT4CodeGenerator.ttinclude
- test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTestDescriptors.cs
- test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTests.cs
Part of Synchronizing connected service and code gen
> Add support for Temp metadata file

- src/CodeGeneration/V4CodeGenDescriptor.cs
- src/Models/ServiceConfiguration.cs
- src/ODataConnectedServiceWizard.cs
- src/Templates/ODataT4CodeGenerator.cs
- src/Templates/ODataT4CodeGenerator.tt
- src/Templates/ODataT4CodeGenerator.ttinclude
- src/ViewModels/AdvancedSettingsViewModel.cs
- src/ViewModels/ConfigODataEndpointViewModel.cs
- src/Views/ConfigODataEndpoint.xaml
- test/ODataConnectedService.Tests/Templates/CodeGenerationContextTest.cs
- test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTests.cs
Part of codegen<>connected service parity
Original Issue: https://github.com/OData/odata.net/issues/1315
Original PR: https://github.com/OData/odata.net/pull/1637
> Add support for Custom Http Headers

- src/CodeGeneration/V4CodeGenDescriptor.cs
- src/ODataConnectedServiceProvider.cs
- src/Properties/AssemblyInfo.cs
- src/source.extension.vsixmanifest
Reverts OData/ODataConnectedService#46
> Revert "Make temp file metadata default"

- test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTests.cs
Fix the issue #41 for all cases:
> Fix #41 : add TransformTool paths for all VS versions

- src/ODataConnectedServiceWizard.cs
- src/Views/ConfigODataEndpoint.xaml
- src/Views/ConfigODataEndpoint.xaml.cs
> Add ability for choosing local metadata files

- src/ODataConnectedServiceWizard.cs
- src/ViewModels/AdvancedSettingsViewModel.cs
- src/ViewModels/ConfigODataEndpointViewModel.cs
- src/ViewModels/OperationImportsViewModel.cs
> Fix #98 : updating Connected Service does not set previously selected options

- src/CodeGeneration/V4CodeGenDescriptor.cs
- src/Templates/ODataT4CodeGenFilesManager.ttinclude
- src/Templates/ODataT4CodeGenerator.cs
- src/Templates/ODataT4CodeGenerator.ttinclude
Fix #96
Also add logging for adding/updating files when generating multiple files.
For adding:
For updating:
> Fix #96 : Updating multiple files prompts to overwrite each file

- src/Templates/ODataT4CodeGenerator.cs
Run custom tool against TT file to fix divergence with the CS file
> Run custom tool against TT file to fix divergence with the CS file

- src/Properties/AssemblyInfo.cs
- src/source.extension.vsixmanifest
> Bump version to 0.9.1

- src/ViewModels/OperationImportsViewModel.cs
- src/ViewModels/SchemaTypesViewModel.cs
> fix Schema types and operation imports naming

- src/ODataConnectedServiceWizard.cs
> Fix #106 : Bug in wizard state persistence in update scenario

- src/Properties/AssemblyInfo.cs
- src/source.extension.vsixmanifest
> Update version to 0.10.0

- README.md
- src/Properties/AssemblyInfo.cs
This PR changes the build status shown in README to point to the new OData/master pipeline
> Change build status in README.md

- azure-pipelines.yml
This PR updates the pipeline to ensure signed vsix are published.
> Update pipeline to publish signed vsix

- test/ODataConnectedService.Tests/Common/EdmHelperTests.cs
- test/ODataConnectedService.Tests/ODataConnectedServiceWizardTests.cs
- test/ODataConnectedService.Tests/TestMetadataCsdl.xml
> Fix #140 : Missed entity type in TestMetadataCsdl.xml file

- test/ODataConnectedService.Tests/CodeGeneration/CodeGenDescriptorTest.cs
- test/ODataConnectedService.Tests/ViewModels/ConfigOdataEndPointViewModelTests.cs
> Fix #143 : Some tests is failed for non "en-US" default culture

- src/Templates/ODataT4CodeGenerator.cs
- src/Templates/ODataT4CodeGenerator.ttinclude
> Fix #151: The name 'Edmx' does not exist in the current context

- .editorconfig
- ODataConnectedService.Tests.sln
- src/CodeGeneration/BaseCodeGenDescriptor.cs
- src/CodeGeneration/V3CodeGenDescriptor.cs
- src/CodeGeneration/V4CodeGenDescriptor.cs
- src/Common/EdmHelper.cs
- src/Common/ProjectHelper.cs
- src/Models/BoundOperationModel.cs
- src/Models/OperationImportModel.cs
- src/Models/SchemaTypeModel.cs
- src/ODataConnectedService.csproj
- src/ODataConnectedServiceHandler.cs
- src/ODataConnectedServiceWizard.cs
- src/ViewModels/AdvancedSettingsViewModel.cs
- src/ViewModels/ConfigODataEndpointViewModel.cs
- src/ViewModels/OperationImportsViewModel.cs
- src/ViewModels/SchemaTypesViewModel.cs
- src/Views/ConfigODataEndpoint.xaml.cs
- src/packages.config
- test/ODataConnectedService.Tests/CodeGeneration/CodeGenDescriptorTest.cs
- test/ODataConnectedService.Tests/ODataConnectedService.Tests.csproj
- test/ODataConnectedService.Tests/ODataConnectedServiceWizardTests.cs
- test/ODataConnectedService.Tests/Templates/ODataClientTemplateUnitTests.cs
- test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTestDescriptors.cs
- test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTests.cs
- test/ODataConnectedService.Tests/Templates/UtilsTests.cs
- test/ODataConnectedService.Tests/TestHelpers/GeneratedCodeHelpers.cs
- test/ODataConnectedService.Tests/TestHelpers/TestVsPackageInstallerServices.cs
- test/ODataConnectedService.Tests/ViewModels/OperationImportsViewModelTests.cs
- test/ODataConnectedService.Tests/ViewModels/SchemaTypesViewModelTests.cs
> Configure FxCop Analyzers

- src/Properties/AssemblyInfo.cs
- src/source.extension.vsixmanifest
> Set version to 0.11.1

- src/Properties/AssemblyInfo.cs
- src/source.extension.vsixmanifest
Bump version to 0.11.2 - To mitigate conflicts during local testing
> Bump version to 0.11.2

- src/Properties/AssemblyInfo.cs
- src/source.extension.vsixmanifest
> Bump up version to 0.12.1

- src/Templates/ODataT4CodeGenerator.cs
- src/Templates/ODataT4CodeGenerator.ttinclude
- test/ODataConnectedService.Tests/CodeGenReferences/AbstractEntityTypeWithoutKey.vb
- test/ODataConnectedService.Tests/CodeGenReferences/DupNamesDSC.vb
- test/ODataConnectedService.Tests/CodeGenReferences/DupNamesWithCamelCase.vb
- test/ODataConnectedService.Tests/CodeGenReferences/DynamicPropertyContainerTest.vb
- test/ODataConnectedService.Tests/CodeGenReferences/EntitiesEnumsFunctionsSelectTypes.vb
- test/ODataConnectedService.Tests/CodeGenReferences/EntityBooleanPropertyWithDefaultValue.vb
- test/ODataConnectedService.Tests/CodeGenReferences/EntityBooleanPropertyWithDefaultValueDSC.vb
- test/ODataConnectedService.Tests/CodeGenReferences/KeywordsAsNames.vb
- test/ODataConnectedService.Tests/CodeGenReferences/MergedFunctionalTest.vb
- test/ODataConnectedService.Tests/CodeGenReferences/MergedFunctionalTestDSC.vb
- test/ODataConnectedService.Tests/CodeGenReferences/MultiReferenceModel.vb
- test/ODataConnectedService.Tests/CodeGenReferences/MultiReferenceModelRelativeUri.vb
- test/ODataConnectedService.Tests/CodeGenReferences/NamespaceInKeywords.vb
- test/ODataConnectedService.Tests/CodeGenReferences/NamespacePrefixWithDoubleNamespaces.vb
- test/ODataConnectedService.Tests/CodeGenReferences/NamespacePrefixWithInheritence.vb
- test/ODataConnectedService.Tests/CodeGenReferences/NamespacePrefixWithSingleNamespace.vb
- test/ODataConnectedService.Tests/CodeGenReferences/OverrideOperations.vb
- test/ODataConnectedService.Tests/CodeGenReferences/PrefixConflictDSC.vb
- test/ODataConnectedService.Tests/CodeGenReferences/UpperCamelCaseWithNamespacePrefix.vb
- test/ODataConnectedService.Tests/CodeGenReferences/UpperCamelCaseWithoutNamespacePrefix.vb
- test/ODataConnectedService.Tests/CodeGenReferences/UpperCamelCaseWithoutNamespacePrefixDSC.vb
- test/ODataConnectedService.Tests/Templates/ODataClientTemplateUnitTests.cs
> Fix #206 : VB.Net generated code does not use NameCsdl.xml

- src/Properties/AssemblyInfo.cs
- src/source.extension.vsixmanifest
> Bump up version 0.13.0

- src/OData.Cli/OData.Cli.csproj
- src/OData.Cli/Program.cs
This PR contains a list of options the <code> odata-cli </code> generate command will have.
> generate proxy command options

- src/ODataConnectedService/ViewModels/ConfigODataEndpointViewModel.cs
- src/ODataConnectedService/Views/ConfigODataEndpoint.xaml
This PR has changes to the ODataConnectedService. The aim is to remove clutter from the ConfigODataEndpoint page and fit all elements to the page without scrolling.
> Feature ocs redesign

- src/Microsoft.OData.Cli/GenerateCommand.cs
https://github.com/OData/ODataConnectedService/issues/296
changed cli return codes
> fix for #296

- src/Microsoft.OData.CodeGen/Microsoft.OData.CodeGen.csproj
Upgrade Newtonsoft.Json dependency to fix vulnerability
> Upgrade Newtonsoft.Json dependency to fix vulnerability

- README.md
> Fix .NET Foundation Code of Conduct Link

- src/ODataConnectedService/Properties/AssemblyInfo.cs
- src/ODataConnectedService/source.extension.vsixmanifest
- src/ODataConnectedService_VS2022Plus/ODataConnectedService_VS2022Plus.csproj
- src/ODataConnectedService_VS2022Plus/Properties/AssemblyInfo.cs
- src/ODataConnectedService_VS2022Plus/source.extension.vsixmanifest
- test/ODataConnectedService.Tests/ODataConnectedService.Tests.csproj
Updates version to v1.0.1
Also updates the referenced VS SDK version curtesy of #337
> Update version to v1.0.1

- azure-pipelines.yml
- src/Microsoft.OData.CodeGen/Templates/ODataT4CodeGenFilesManager.ttinclude
> add vs2022plus.dll to .tt file.

- src/ODataConnectedService_VS2022Plus/source.extension.vsixmanifest
Fixes https://github.com/OData/ODataConnectedService/issues/374, https://github.com/OData/ODataConnectedService/issues/375
> support arm64 product architecture

- src/Microsoft.OData.CodeGen/Microsoft.OData.CodeGen.csproj
- src/ODataConnectedService.Shared/Common/EdmHelper.cs
- src/ODataConnectedService.Shared/Common/ExtensionMethods.cs
- src/ODataConnectedService.Shared/Common/ProjectHelper.cs
- src/ODataConnectedService.Shared/Common/UserSettingsPersistenceHelper.cs
- src/ODataConnectedService.Shared/ViewModels/OperationImportsViewModel.cs
- src/ODataConnectedService.Shared/ViewModels/SchemaTypesViewModel.cs
- src/ODataConnectedService/Properties/AssemblyInfo.cs
- test/ODataConnectedService.Tests/CodeGeneration/CodeGenDescriptorTest.cs
- test/ODataConnectedService.Tests/ODataConnectedServiceHandlerTest.cs
- test/ODataConnectedService.Tests/ODataConnectedServiceWizardTests.cs
- test/ODataConnectedService.Tests/Templates/ODataClientTemplateUnitTests.cs
- test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTestDescriptors.cs
- test/ODataConnectedService.Tests/Templates/UniqueIdentifierServiceTests.cs
- test/ODataConnectedService.Tests/ViewModels/SchemaTypesViewModelTests.cs
This pull request fixes dependencies and code violations warnings
> Fix dependencies and code violations warnings

- src/Microsoft.OData.Cli/Microsoft.OData.Cli.csproj
- src/ODataConnectedService/Properties/AssemblyInfo.cs
- src/ODataConnectedService/source.extension.vsixmanifest
- src/ODataConnectedService_VS2022Plus/Properties/AssemblyInfo.cs
- src/ODataConnectedService_VS2022Plus/source.extension.vsixmanifest
Bump version to 1.1.0 (CLI 0.3.0)
> Bump version to 1.1.0 (CLI 0.3.0)

- src/Microsoft.OData.Cli/Microsoft.OData.Cli.csproj
- src/ODataConnectedService/Properties/AssemblyInfo.cs
- src/ODataConnectedService/source.extension.vsixmanifest
- src/ODataConnectedService_VS2022Plus/Properties/AssemblyInfo.cs
- src/ODataConnectedService_VS2022Plus/source.extension.vsixmanifest
Bump version to 1.1.1 (CLI 0.3.1)
> Bump version to 1.1.1 (CLI 0.3.1)

- src/ODataConnectedService/Properties/AssemblyInfo.cs
- src/ODataConnectedService/source.extension.vsixmanifest
- src/ODataConnectedService_VS2022Plus/Properties/AssemblyInfo.cs
- src/ODataConnectedService_VS2022Plus/source.extension.vsixmanifest
Bump version to 1.1.2 (CLI 0.3.2)
> Update version to 1.1.0 (CLI 0.3.1)

- src/Microsoft.OData.CodeGen/CodeGeneration/V4CodeGenDescriptor.cs
- src/Microsoft.OData.CodeGen/Templates/ODataT4CodeGenFilesManager.ttinclude
- src/Microsoft.OData.CodeGen/Templates/ODataT4CodeGenerator.cs
- src/Microsoft.OData.CodeGen/Templates/ODataT4CodeGenerator.ttinclude
- src/ODataConnectedService.Shared/ConnectedServiceFileHandler.cs
- src/ODataConnectedService.Shared/ConnectedServicePackageInstaller.cs
- test/ODataConnectedService.Tests/CodeGeneration/CodeGenDescriptorTest.cs
- test/ODataConnectedService.Tests/ViewModels/ConfigOdataEndPointViewModelTests.cs
Updates codegen to be async and builds on top of #413
> Migrate codegen to async

- src/ODataConnectedService/Properties/AssemblyInfo.cs
- src/ODataConnectedService/source.extension.vsixmanifest
- src/ODataConnectedService_VS2022Plus/Properties/AssemblyInfo.cs
- src/ODataConnectedService_VS2022Plus/source.extension.vsixmanifest
Bump version to 1.1.1 to release connected service
> Bump version to 1.1.1
