OData/ODataConnectedService

- src/Templates/ODataT4CodeGenerator.cs
- src/Templates/ODataT4CodeGenerator.ttinclude
The template file in the codebase (`ODataT4CodeGenerator.ttinclude`) was incorrect, it's an outdated version from an old commit that added the `internal` modifier to both method and classes when `MakeTypesInternal` is set to true. However, this generated code that had build errors because internal methods can't implement interfaces (e.g. `INotifyChanged`), this was fixed by a later commit. But it appears that during a rebase, the outdated template fail was retained instead of the corrected one. This PR fixes that issue, removing the internal class modifier from methods that should be public.
Note the `ODataT4CodeGenerator.cs` file was still correct, and that's why tests were still passing.
> Fix outdated template file to match code generator

- src/ODataConnectedService.csproj
- src/packages.config
- test/ODataConnectedService.Tests/ODataConnectedService.Tests.csproj
This pull requests upgrades  `Microsoft.OData.Client` library to the latest version `7.6.3`
> upgrade Microsoft.OData.Client to version 7.6.3

- src/Templates/ODataT4CodeGenerator.cs
- src/Templates/ODataT4CodeGenerator.ttinclude
- test/ODataConnectedService.Tests/CodeGenReferences/AbstractEntityTypeWithoutKeyDSC.cs
- test/ODataConnectedService.Tests/CodeGenReferences/DupNames.cs
- test/ODataConnectedService.Tests/CodeGenReferences/DupNamesWithCamelCaseDSC.cs
- test/ODataConnectedService.Tests/CodeGenReferences/EntitiesEnumsFunctions.cs
- test/ODataConnectedService.Tests/CodeGenReferences/EntitiesEnumsFunctionsDSC.cs
- test/ODataConnectedService.Tests/CodeGenReferences/EntitiesEnumsFunctionsDSCWithInternalTypes.cs
- test/ODataConnectedService.Tests/CodeGenReferences/EntitiesEnumsFunctionsWithInternalTypes.cs
- test/ODataConnectedService.Tests/CodeGenReferences/EntityHierarchyWithIDAndIdDSC.cs
- test/ODataConnectedService.Tests/CodeGenReferences/KeywordsAsNames.cs
- test/ODataConnectedService.Tests/CodeGenReferences/MergedFunctionalTest.cs
- test/ODataConnectedService.Tests/CodeGenReferences/MergedFunctionalTestDSC.cs
- test/ODataConnectedService.Tests/CodeGenReferences/NamespaceInKeywords.cs
- test/ODataConnectedService.Tests/CodeGenReferences/NamespacePrefixRepeatWithSchemaNameSpace.cs
- test/ODataConnectedService.Tests/CodeGenReferences/NamespacePrefixWithDoubleNamespaces.cs
- test/ODataConnectedService.Tests/CodeGenReferences/NamespacePrefixWithInheritence.cs
- test/ODataConnectedService.Tests/CodeGenReferences/NamespacePrefixWithSingleNamespace.cs
- test/ODataConnectedService.Tests/CodeGenReferences/OverrideOperationsDSC.cs
- test/ODataConnectedService.Tests/CodeGenReferences/PrefixConflict.cs
- test/ODataConnectedService.Tests/CodeGenReferences/UpperCamelCaseWithNamespacePrefix.cs
- test/ODataConnectedService.Tests/CodeGenReferences/UpperCamelCaseWithoutNamespacePrefix.cs
- test/ODataConnectedService.Tests/CodeGenReferences/UpperCamelCaseWithoutNamespacePrefixDSC.cs
This pull request is part of codegen/connected service migration. makes use of `CsdlReader.TryParse(..)` instead of `CsdlReader.Parse(...)`.
> Use CsdlReader.TryParse(..) instead of CsdlReader.Parse(..)

- src/CodeGeneration/BaseCodeGenDescriptor.cs
- src/CodeGeneration/V3CodeGenDescriptor.cs
- src/CodeGeneration/V4CodeGenDescriptor.cs
- src/Common/Constants.cs
- src/ODataConnectedServiceHandler.cs
- test/ODataConnectedService.Tests/CodeGeneration/V4CodeGenDescriptorTest.cs
- test/ODataConnectedService.Tests/ODataConnectedServiceHandlerTest.cs
1) Add `Async` suffix to async methods;
2) Remove [Microsoft WCF ToolKit](https://download.microsoft.com/download/1/C/A/1CAA41C7-88B9-42D6-9E11-3C655656DAB1/WcfDataServices.exe) dependency: no need to install it to generate client code for **OData v3**.
> Remove Microsoft WCF ToolKit dependency

- src/Templates/ODataT4CodeGenerator.cs
- src/Templates/ODataT4CodeGenerator.ttinclude
- test/ODataConnectedService.Tests/CodeGenReferences/AbstractEntityTypeWithoutKeyDSC.cs
- test/ODataConnectedService.Tests/CodeGenReferences/DupNames.cs
- test/ODataConnectedService.Tests/CodeGenReferences/DupNamesWithCamelCaseDSC.cs
- test/ODataConnectedService.Tests/CodeGenReferences/EntitiesEnumsFunctions.cs
- test/ODataConnectedService.Tests/CodeGenReferences/EntitiesEnumsFunctionsDSC.cs
- test/ODataConnectedService.Tests/CodeGenReferences/EntitiesEnumsFunctionsDSCWithInternalTypes.cs
- test/ODataConnectedService.Tests/CodeGenReferences/EntitiesEnumsFunctionsWithInternalTypes.cs
- test/ODataConnectedService.Tests/CodeGenReferences/EntityHierarchyWithIDAndIdDSC.cs
- test/ODataConnectedService.Tests/CodeGenReferences/KeywordsAsNames.cs
- test/ODataConnectedService.Tests/CodeGenReferences/MergedFunctionalTest.cs
- test/ODataConnectedService.Tests/CodeGenReferences/MergedFunctionalTestDSC.cs
- test/ODataConnectedService.Tests/CodeGenReferences/MultiReferenceModel.cs
- test/ODataConnectedService.Tests/CodeGenReferences/NamespaceInKeywords.cs
- test/ODataConnectedService.Tests/CodeGenReferences/NamespaceInKeywordsWithRefModel.cs
- test/ODataConnectedService.Tests/CodeGenReferences/NamespacePrefixRepeatWithSchemaNameSpace.cs
- test/ODataConnectedService.Tests/CodeGenReferences/NamespacePrefixWithDoubleNamespaces.cs
- test/ODataConnectedService.Tests/CodeGenReferences/NamespacePrefixWithInheritence.cs
- test/ODataConnectedService.Tests/CodeGenReferences/NamespacePrefixWithSingleNamespace.cs
- test/ODataConnectedService.Tests/CodeGenReferences/OverrideOperationsDSC.cs
- test/ODataConnectedService.Tests/CodeGenReferences/PrefixConflict.cs
- test/ODataConnectedService.Tests/CodeGenReferences/Simple.cs
- test/ODataConnectedService.Tests/CodeGenReferences/SimpleDSC.cs
- test/ODataConnectedService.Tests/CodeGenReferences/UnexpectedElementsAndAttributes.cs
- test/ODataConnectedService.Tests/CodeGenReferences/UpperCamelCaseWithNamespacePrefix.cs
- test/ODataConnectedService.Tests/CodeGenReferences/UpperCamelCaseWithoutNamespacePrefix.cs
- test/ODataConnectedService.Tests/CodeGenReferences/UpperCamelCaseWithoutNamespacePrefixDSC.cs
This was previously merged. We are recreating it so that it can be cherry picked for release.
We are allowing ByKey method to receive an IDictionary<string, object> instead of the concrete class Dictionary<string, object>
> Replace Dictionary with IDictionary

- src/ODataConnectedServiceProvider.cs
- src/source.extension.vsixmanifest
Now that 0.5.0 is out this bumps the version up so that the release from master has a new version number.
> version bump to target probable next release

- src/CodeGeneration/V4CodeGenDescriptor.cs
- src/ODataConnectedService.csproj
- src/ODataConnectedServiceWizard.cs
- src/Views/ConfigODataEndpoint.xaml
Fixes issue #49 
This PR fixes regression issues in PR #27 
*Issues fixed*
An exception was being thrown when `custom http headers` was null/empty.
We have enhanced the view by adding a text tool tip for the CustomHttpHeaders textbox
Enabled the ConfigODataEndpoint view during Connected service update
> Custom http headers enhancements

- src/CodeGeneration/BaseCodeGenDescriptor.cs
- src/CodeGeneration/V4CodeGenDescriptor.cs
We usually store the metadata in a string variable. We have the option of specifying a temp metadata file path where we store the metadata in an xml file. 
This PR makes the temp metadata file the default practice.
> Make temp file metadata default

- src/Properties/AssemblyInfo.cs
- src/ViewModels/ConfigODataEndpointViewModel.cs
- src/source.extension.vsixmanifest
Fixes issue #75
The cause was that the `ResetDataContext()` method, which sets the service name to the default, was being called in the page entering event (which happens after the page has been initialized with values loaded from saved data). I've moved that method to the constructor.
Also updated the version to 0.7.1 so that I can make a patch release after this is merged.
> Fix bug: saved service name is overwritten with default when updating client

- src/Properties/AssemblyInfo.cs
- src/source.extension.vsixmanifest
Bump dev version to 0.7.2 so that we don't get conflicts when debugging in case we've installed the 0.7.1 locally
> Bump version for development

- src/Common/ExtensionsHelper.cs
- src/Models/ServiceConfiguration.cs
- src/Models/UserSettings.cs
- src/ODataConnectedService.csproj
- src/ODataConnectedServiceWizard.cs
- src/ViewModels/AdvancedSettingsViewModel.cs
- src/ViewModels/ConfigODataEndpointViewModel.cs
- src/Views/AdvancedSettings.xaml
- src/Views/ConfigODataEndpoint.xaml
- src/Views/ConfigODataEndpoint.xaml.cs
- src/packages.config
This PR adds support for loading ODataConnectedService wizard configs from a .json file. 
The following is a sample .json file to load 
<pre>
{
"ExtendedData": {
"ExcludedOperationImports": [],
"EnableNamingAlias": false,
"IgnoreUnexpectedElementsAndAttributes": false,
"IncludeT4File": false,
"ServiceName": "OData Service",
"Endpoint": "https://services.odata.org/v4/TripPinServiceRW/$metadata",
"GeneratedFileNamePrefix": "Test",
"UseNamespacePrefix": true,
"NamespacePrefix":"Test",
"UseDataServiceCollection": true,
"MakeTypesInternal": false,
"OpenGeneratedFilesInIDE": true,
"GenerateMultipleFiles":false,
"CustomHttpHeaders": null,
"IncludeWebProxy": false,
"WebProxyHost": null,
"IncludeWebProxyNetworkCredentials": false,
"WebProxyNetworkCredentialsUsername": null, …
> Add support for loading configs from a config file

- src/Models/UserSettings.cs
- src/ODataConnectedServiceWizard.cs
- src/ViewModels/AdvancedSettingsViewModel.cs
- src/ViewModels/ConfigODataEndpointViewModel.cs
- src/ViewModels/OperationImportsViewModel.cs
- src/Views/ConfigODataEndpoint.xaml
- src/Views/ConfigODataEndpoint.xaml.cs
Fix #69, fix #94
Refactored `ODataConnectedServiceWizard`:
* extract `PageEntering`-methods
* rename `ObjectSelectionViewModel_PageEntering` to `OperationImportsViewModel_PageEntering`
* update **Operation Imports** only for the new Endpoints
> Fix issue #69: saving the wizard pages state

- src/CodeGeneration/V4CodeGenDescriptor.cs
- src/Common/Constants.cs
- src/ODataConnectedService.csproj
- src/Templates/ODataT4CodeGenerator.cs
- src/Templates/ODataT4CodeGenerator.tt
- src/Templates/ODataT4CodeGenerator.ttinclude
- src/packages.config
- test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTests.cs
Fixes Issue: #54 
_Background_
The current directory when the connected service is running during code generation may be different from when the project itself is running. Therefore we need a way for the generated Csdl.xml to be accessed by the connected service.
Using `relative path` requires us to handle the paths to the working directory for project and connected service which create additional complexity.
`Absolute path` would solve this. The main drawback is that when you move the project folder to another folder, we will need to regenerate the files afresh since the path will be invalid.
**Solution**
We make the Csdl.xml an embedded resource which will be shipped with the executable. With this we will not have to worry about paths.
> Make temp file metadata an embedded resource

- src/ODataConnectedServiceWizard.cs
- src/ViewModels/SchemaTypesViewModel.cs
Added some fixes to PR # 99, which I did not manage to add before merging with rebase:
* Fixed loading `SchemaTypes` without going though `SchemaTypes` wizard page when updating a connected service;
* Fixed loading `SchemaTypes` when endpoint was changed.
> Fix #99 : Add some fixes to PR #99

- src/Views/ConfigODataEndpoint.xaml
- src/Views/ConfigODataEndpoint.xaml.cs
Hi,
The endpoint drop-down contains the recent endpoints that were used.
When working on a server-client app that requires frequent changes to the server and re-generation of the client entities, any redundant click is tedious.
This PR changes the `ComboBox` to auto-select the first URL.
> Auto selects last metadata endpoint

- src/CodeGeneration/V4CodeGenDescriptor.cs
- src/Templates/ODataT4CodeGenFilesManager.ttinclude
- src/Templates/ODataT4CodeGenerator.cs
- src/Templates/ODataT4CodeGenerator.ttinclude
- test/ODataConnectedService.Tests/ODataConnectedService.Tests.csproj
- test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTests.cs
This pull request fixes #57 
It was made possible to generate multiple files using connected service. However, it was only possible while adding this option in connected service UI that executes T4 templates at runtime. This changes allows users to set configuration `GenerateMultipleFiles ` in .`tt` file to true and generate multiple files at desin-time. 
In addition this change also generates `ExtensionMethods `class in a separate file as suggested.
> Enable multiple files generation using design-time T4 templates

- src/Common/UserSettingsPersistenceHelper.cs
- src/Models/SchemaTypeModel.cs
- src/ODataConnectedServiceWizard.cs
- src/ViewModels/OperationImportsViewModel.cs
- test/ODataConnectedService.Tests/ODataConnectedService.Tests.csproj
- test/ODataConnectedService.Tests/ODataConnectedServiceWizardTests.cs
- test/ODataConnectedService.Tests/Properties/AssemblyInfo.cs
- test/ODataConnectedService.Tests/TestMetadataCsdl.xml
- test/ODataConnectedService.Tests/TestMetadataCsdlSimple.xml
- test/ODataConnectedService.Tests/TestMetadataCsdlV3.xml
Addresses #59 
Tests the following functionality:
and use it to populate the view models accordingly. Test that the right fields are set to the view
models based on the saved config
ensure that these fields are disabled (e.g. T4 templates, Service Name, Service Endpoint, Generate multiple files, etc.)
in the view models.
and service config, and returns that. The result of this method will be passed to the `ODataConnectedServiceHandler` so
testing this is critical in ensuring that values will be correctly propagated to the handler
- I also fixed this bug (which I discovered because it caused some tests to fail): #120 
- **Note** These tests set and reset user settings multiple times. This functionality is not mocked, and it does at least affect the settings in the experimental VS instance …
> Add connected service wizard tests

- src/Common/Constants.cs
- src/Models/UserSettings.cs
- src/ODataConnectedServiceWizard.cs
- src/ViewModels/ConfigODataEndpointViewModel.cs
- test/ODataConnectedService.Tests/CodeGenReferences/TempSimple.xml
- test/ODataConnectedService.Tests/ODataConnectedService.Tests.csproj
- test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTest.cs
- test/ODataConnectedService.Tests/ViewModels/ConfigOdataEndPointViewModelTests.cs
Handles the endpoint config page of the wizard, also fetches the model from the provided endpoint.
`OnPageLeavingAsync()` is called when the page is leaving, and it handles a lot of logic that's not tested:
> Adding test cases for ConfigODataEndPointViewModel Class

- src/Common/UserSettingsPersistenceHelper.cs
- test/ODataConnectedService.Tests/ODataConnectedService.Tests.csproj
- test/ODataConnectedService.Tests/Views/UserSettingsTest.cs
Adding Test cases for the following usecases:
- Saves settings when Save() is called
- Loads previously saved settings when Load() is called, returns an instance of UserSettings
- AddToTopOfMruList should add/move the item at the top of the list, without duplicating it if it already exists and without exceeding the maximum allowed entries (10 items)
> Add UserSettings tests

- src/CodeGeneration/V4CodeGenDescriptor.cs
- src/Common/Constants.cs
- test/ODataConnectedService.Tests/CodeGeneration/CodeGenDescriptorTest.cs
- test/ODataConnectedService.Tests/CodeGeneration/TestConfigBasic.txt
- test/ODataConnectedService.Tests/CodeGeneration/TestConfigBasicVB.txt
- test/ODataConnectedService.Tests/ViewModels/ConfigOdataEndPointViewModelTests.cs
Fix #111 
When you add multiple connected services in one project, all csdl files are named `Cdsl.xml`
This causes an exception when reading the embedded resource file since we were trying to read `Csdl.xml` file yet there are multiple of them.
Solution
We are renaming `Csdl.xml` to `[ServiceName]Csdl.xml` to make them unique.
> Fix exception when there are multiple cdsl files

- src/CodeGeneration/V4CodeGenDescriptor.cs
- src/ODataConnectedServiceHandler.cs
- test/ODataConnectedService.Tests/ODataConnectedServiceHandlerTest.cs
- test/ODataConnectedService.Tests/Views/UserSettingsTest.cs
> Add OdataConnectedServiceHandler tests

- src/CodeGeneration/V4CodeGenDescriptor.cs
- src/Templates/ODataT4CodeGenerator.cs
- src/Templates/ODataT4CodeGenerator.tt
- src/Templates/ODataT4CodeGenerator.ttinclude
- test/ODataConnectedService.Tests/CodeGeneration/CodeGenDescriptorTest.cs
- test/ODataConnectedService.Tests/CodeGeneration/TestConfigAllOptionsSet.txt
- test/ODataConnectedService.Tests/CodeGeneration/TestConfigBasic.txt
- test/ODataConnectedService.Tests/CodeGeneration/TestConfigBasicVB.txt
> Fix #115: MetadataDocumentUri not properly escaping local file paths when generating T4 templates

- src/ODataConnectedServiceWizard.cs
- src/ViewModels/OperationImportsViewModel.cs
- src/ViewModels/SchemaTypesViewModel.cs
- test/ODataConnectedService.Tests/ODataConnectedService.Tests.csproj
- test/ODataConnectedService.Tests/ODataConnectedServiceWizardTests.cs
- test/ODataConnectedService.Tests/ViewModels/SchemaTypesViewModelTests.cs
Fix #114 :
* when an schema type is deselected, all the types of its Navigational properties are automatically deselected;
* deselect all operations that require the deselected types.
Added the tests below:
To **ODataConnectedServiceWizardTests**:
To **SchemaTypesViewModelTests**:
> Fix #114: Unselecting all schema types does not deselect dependent function imports

- test/ODataConnectedService.Tests/CodeGeneration/CodeGenDescriptorTest.cs
- test/ODataConnectedService.Tests/Common/EdmHelperTests.cs
- test/ODataConnectedService.Tests/ODataConnectedService.Tests.csproj
- test/ODataConnectedService.Tests/TestMetadataCsdl.xml
> Add EdmHelper Tests

- test/ODataConnectedService.Tests/Common/ProjectHelperTests.cs
- test/ODataConnectedService.Tests/ODataConnectedService.Tests.csproj
Adding tests for ProjectHelpers for working with the VS project.
> Add Project Helper tests

- src/ViewModels/SchemaTypesViewModel.cs
- test/ODataConnectedService.Tests/ViewModels/SchemaTypesViewModelTests.cs
Fix #135
Added the tests below:
To **SchemaTypesViewModelTests:**
> Fix #135 : Collection of enum properties is not added to related types Dictionary for structured types

- src/ViewModels/OperationImportsViewModel.cs
- src/Views/OperationImports.xaml
- test/ODataConnectedService.Tests/ODataConnectedServiceWizardTests.cs
Add a feature #145:
Updated the tests below:
In **ODataConnectedServiceWizardTests:**
> Feature #145 : Showing the operation imports count

- src/Common/EdmHelper.cs
- src/Converters/BoolToVisibilityConverter.cs
- src/Models/OperationImportModel.cs
- src/ODataConnectedService.csproj
- src/ViewModels/OperationImportsViewModel.cs
- src/Views/OperationImports.xaml
- test/ODataConnectedService.Tests/Common/EdmHelperTests.cs
- test/ODataConnectedService.Tests/Converters/BoolToVisibilityConverterTests.cs
- test/ODataConnectedService.Tests/ODataConnectedService.Tests.csproj
- test/ODataConnectedService.Tests/ODataConnectedServiceWizardTests.cs
- test/ODataConnectedService.Tests/ViewModels/ConfigOdataEndPointViewModelTests.cs
- test/ODataConnectedService.Tests/ViewModels/OperationImportsViewModelTests.cs
Add feature #127
Added the tests below:
To **EdmHelperTests:**
To **BoolToVisibilityConverterTests:**
> Feature #127 : Option to show operation return types and list of operation parameters

- src/ViewModels/OperationImportsViewModel.cs
- src/ViewModels/SchemaTypesViewModel.cs
- src/Views/OperationImports.xaml
- src/Views/SchemaTypes.xaml
- test/ODataConnectedService.Tests/ViewModels/OperationImportsViewModelTests.cs
- test/ODataConnectedService.Tests/ViewModels/SchemaTypesViewModelTests.cs
Fix #158 :
Added the tests below:
To **SchemaTypesViewModelTests:**
To **OperationImportsViewModelTests:**
> Fix #158 : Search box for oData entitities to add

- src/Common/ExtensionMethods.cs
- src/Common/UserSettingsPersistenceHelper.cs
- src/Models/ServiceConfiguration.cs
- src/Models/UserSettings.cs
- src/ODataConnectedService.csproj
- src/ODataConnectedServiceWizard.cs
- src/Properties/AssemblyInfo.cs
- src/ViewModels/AdvancedSettingsViewModel.cs
- src/ViewModels/ConfigODataEndpointViewModel.cs
- src/ViewModels/OperationImportsViewModel.cs
- src/Views/AdvancedSettings.xaml
- src/Views/ConfigODataEndpoint.xaml
- src/Views/ConfigODataEndpoint.xaml.cs
- src/source.extension.vsixmanifest
- test/ODataConnectedService.Tests/Common/ExtensionMethodsTests.cs
- test/ODataConnectedService.Tests/ODataConnectedService.Tests.csproj
- test/ODataConnectedService.Tests/ODataConnectedServiceWizardTests.cs
- test/ODataConnectedService.Tests/ViewModels/ConfigOdataEndPointViewModelTests.cs
- test/ODataConnectedService.Tests/Views/UserSettingsTest.cs
This pull request fixes #181 
Set the most logical config defaults for the wizard. Below is a detailed explanation of the changes:
1. Restore OCS wizard default settings that were inadvertently dropped with the introduction of the settings persistence feature, i.e.
- GeneratedFileNamePrefix => `Reference`
- NamespacePrefix => `Reference`
- UseDataServiceCollection => `true`
- EnableNamingAlias => `true`
- IgnoreUnexpectedElementsAndAttributes => `true`
- ServiceName => `OData Service` 
2. ~Fix handling of **most recently used** (MRU) endpoints. Presently, the `UserSettings` class exposes MRU endpoints as an `ObservableCollection` that one is able to manipulate directly (add/remove/etc) and violate the whole idea of "most recently used". This is fixed by changing `MruEndpoints` property …
> Set the most logical config defaults for the wizard

- src/CodeGeneration/V4CodeGenDescriptor.cs
This pull request fixes #195
Fix warnings as a result of an empty metadata file generated when user opts to include T4 file.
By pre-populating the file with the root element to suppress the warnings. That content is later overwritten when the metadata is written to the file [here](https://github.com/OData/ODataConnectedService/blob/ef08797cbbf2e8b6809d88dd9142f95de61c8710/src/Templates/ODataT4CodeGenerator.cs#L4492) - `append: false` to overwrite the file
> Fix warnings as a result of an empty metadata file generated when user opts to include T4 file

- src/Models/UserSettings.cs
- test/ODataConnectedService.Tests/ODataConnectedServiceWizardTests.cs
> Restore default for client proxy to namespace in the metadata document

- src/Models/ServiceConfiguration.cs
- src/Models/UserSettings.cs
- src/ODataConnectedServiceHandler.cs
- src/Views/ConfigODataEndpoint.xaml
- test/ODataConnectedService.Tests/ODataConnectedServiceHandlerTest.cs
- test/ODataConnectedService.Tests/ODataConnectedServiceWizardTests.cs
Allow users to store custom Http headers and proxy credentials in `ConnectedService.json`.
Adds a checkbox to "Include Custom Http Headers" and "Include Proxy Network Credentials" allowing the user to store these in `ConnectedService.json` if so desired.
> Allow users to store custom Http headers and proxy credentials

- src/Microsoft.OData.CodeGen/Templates/ODataT4CodeGenerator.ttinclude
Currently, if we run custom tool on the tt template, we get a diff that changes the `ODataT4CodeGenerator` modifier from `public` to `interna`l. This is because the `.cs` file was modified but the `tt` file wasn't. This PR fixes that issue.
> Make ODataT4CodeGenerator public

- src/Microsoft.OData.Cli/GenerateCommand.cs
- src/Microsoft.OData.CodeGen/Common/MetadataReader.cs
- src/Microsoft.OData.CodeGen/Microsoft.OData.CodeGen.csproj
- src/Microsoft.OData.CodeGen/Templates/ODataT4CodeGenerator.cs
- src/Microsoft.OData.CodeGen/Templates/ODataT4CodeGenerator.ttinclude
- src/ODataConnectedService.Shared/ViewModels/ConfigODataEndpointViewModel.cs
- src/ODataConnectedService.Shared/Views/ConfigODataEndpoint.xaml.cs
- src/ODataConnectedService_VS2022Plus/ODataConnectedService_VS2022Plus.csproj
- test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorUnitTest.cs
- test/ODataConnectedService.Tests/ViewModels/ConfigOdataEndPointViewModelTests.cs
This PR fixes the issue https://github.com/OData/ODataConnectedService/issues/48
and is an add on to a contributor's (https://github.com/dr-consit) PR https://github.com/OData/ODataConnectedService/pull/237
It ensures the OData Endpoint URI does not get distorted when the URI includes query and fragment segments.
Before fix
A URI like 'http://localhost:5000/odata/$metadata?api-version=1.0' would have $metadata appended to the end of the URI which would make the OData service inaccessible.
After fix
$metadata, query and fragment segments maintain the correct position and order.
> Improve metadata uri handling

- src/Microsoft.OData.Cli/GenerateCommand.cs
- src/Microsoft.OData.Cli/GenerateOptions.cs
Fix #269 
- Add new option --no-tracking to control the UseDataServiceCollection property of the generator
- Default to false to be aligned with the naming of this option, so it is a breaking change
> Implement "No tracking" option for odata-cli

- src/Microsoft.OData.Cli/PackageInstallers/PackageInstallerHelpers.cs
I've added a minor change so the build can run again. The version for the OData-CLI had already been updated to v0.2.0
> rerun build

- src/Microsoft.OData.Cli/GenerateCommand.cs
Update GenerateCommand.cs as suggested in #268 to allow odata-cli to generate internal classes.
Fixes issue #268
> Make odata-cli honor internal option (issue #268)

- src/Microsoft.OData.Cli/GenerateCommand.cs
- src/Microsoft.OData.Cli/GenerateOptions.cs
- src/Microsoft.OData.CodeGen/CodeGeneration/V4CodeGenDescriptor.cs
- src/Microsoft.OData.CodeGen/Microsoft.OData.CodeGen.csproj
- src/Microsoft.OData.CodeGen/Models/ServiceConfiguration.cs
- src/Microsoft.OData.CodeGen/Templates/ODataT4CodeGenerator.cs
- src/Microsoft.OData.CodeGen/Templates/ODataT4CodeGenerator.tt
- src/Microsoft.OData.CodeGen/Templates/ODataT4CodeGenerator.ttinclude
- src/ODataConnectedService.Shared/Models/UserSettings.cs
- src/ODataConnectedService.Shared/ODataConnectedServiceWizard.cs
- src/ODataConnectedService.Shared/Views/AdvancedSettings.xaml
- test/ODataConnectedService.Tests/CodeGeneration/CodeGenDescriptorTest.cs
- test/ODataConnectedService.Tests/CodeGeneration/TestConfigAllOptionsSet.txt
- test/ODataConnectedService.Tests/CodeGeneration/TestConfigBasic.txt
- test/ODataConnectedService.Tests/CodeGeneration/TestConfigBasicVB.txt
- test/ODataConnectedService.Tests/Common/ExtensionMethodsTests.cs
- test/ODataConnectedService.Tests/ODataConnectedServiceWizardTests.cs
- test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTest.cs
- test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTests.cs
- test/ODataConnectedService.Tests/TestHelpers/GeneratedCodeHelpers.cs
- test/ODataConnectedService.Tests/Views/UserSettingsTest.cs
Add the NoTimestamp option to disable the Generated date timestamp in generated files.
Added to OData-CLI and to VS Extension
Tests added and updated to take into account NoTimestamp option
Fixes #349
> Add no timestamp option (issue #349)

- src/ODataConnectedService.Shared/ConnectedServiceFileHandler.cs
This pull request fixes issue #380 
When entity is an open type (`<EntityType Name="ResultObject" OpenType="true">`) VS extension generates `IDictionary<string, object> DynamicProperties` property. 
This property must have `ContainerProperty` attribute. 
Otherwise, when connected service is used, the dictionary is not populated from response.
If in the project, referenced `Microsoft.OData.Client` nuget with version >= 7.10.*, `ContainerProperty` attribute not added due to wrong versions comparison.
If I reference `Microsoft.OData.Client` version 7.20.0, the `ContainerProperty` attribute not added because lexically 7.20.0 < 7.6.4
Fix `Microsoft.OData.Client` versions comparison.
> Fix missing ContainerProperty attribute on dynamic properties (issue #380)

- azure-pipelines.yml
- configs/filelist.txt
This pull request
- updates publisher name on the pipeline
- adds `exe` as a target file type for OData CLI signing since it's an executable command line tool - signing still works without this change.
- adds `Microsoft.OData.Cli.dll`, `Microsoft.OData.CodeGen.dll` and `Microsoft.OData.Cli.exe` to the file list referenced during signing  - signing still works without this change.
> Update publisher name on pipeline

- src/Microsoft.OData.CodeGen/Templates/ODataT4CodeGenerator.cs
- src/Microsoft.OData.CodeGen/Templates/ODataT4CodeGenerator.ttinclude
- test/Microsoft.OData.Cli.Tests/CodeGeneration/Artifacts/SampleServiceV4EnableInternalProxy.cs
- test/Microsoft.OData.Cli.Tests/CodeGeneration/Artifacts/SampleServiceV4EnableTrackingProxy.cs
- test/Microsoft.OData.Cli.Tests/CodeGeneration/Artifacts/SampleServiceV4ExcludedBoundOperationsProxy.cs
- test/Microsoft.OData.Cli.Tests/CodeGeneration/Artifacts/SampleServiceV4ExcludedOperationImportsProxy.cs
- test/Microsoft.OData.Cli.Tests/CodeGeneration/Artifacts/SampleServiceV4ExcludedSchemaTypesProxy.cs
- test/Microsoft.OData.Cli.Tests/CodeGeneration/Artifacts/SampleServiceV4MultipleFilesProxy.cs
- test/Microsoft.OData.Cli.Tests/CodeGeneration/Artifacts/SampleServiceV4MultipleOptionsProxy.cs
- test/Microsoft.OData.Cli.Tests/CodeGeneration/Artifacts/SampleServiceV4NamespacePrefixProxy.cs
- test/Microsoft.OData.Cli.Tests/CodeGeneration/Artifacts/SampleServiceV4Proxy.cs
- test/Microsoft.OData.Cli.Tests/CodeGeneration/Artifacts/SampleServiceV4ServiceNameProxy.cs
- test/Microsoft.OData.Cli.Tests/CodeGeneration/Artifacts/SampleServiceV4UpperCamelCaseProxy.cs
Fixes #405 
We store the CSDL file as an embedded resource. When we want to load the and parse the CSDL in memory, we find the resource that matches the target CSDL file name. We use `resourceName.EndsWith(filePath)` to find the match. However, this causes a conflict when one CSDL name is a substring of the other, e.g.:
- `OData ServiceCsdl.xml`
- `Another OData ServiceCsdl.xml`
Currently an exception is thrown when such a conflict is detected. This PR fixes this issue by resolving the conflict by selecting the shortest resource name that ends with the target filename.
This solves the problem for simple cases, and possibly all practical common scenarios. However, it would be problematic in the following cases:
- The user manually creates a file called `OData ServiceCsdl.xml` in the same …
> Resolve conflicts when two csdl names have similar suffixes

- src/ODataConnectedService.Shared/ODataConnectedServiceWizard.cs
- src/ODataConnectedService.Shared/ViewModels/OperationImportsViewModel.cs
- src/ODataConnectedService.Shared/ViewModels/SchemaTypesViewModel.cs
- src/ODataConnectedService.Shared/Views/OperationImports.xaml
- src/ODataConnectedService.Shared/Views/OperationImports.xaml.cs
- src/ODataConnectedService.Shared/Views/SchemaTypes.xaml
- src/ODataConnectedService.Shared/Views/SchemaTypes.xaml.cs
- src/ODataConnectedService/source.extension.vsixmanifest
- src/ODataConnectedService_VS2022Plus/ODataConnectedService_VS2022Plus.csproj
- test/ODataConnectedService.Tests/ODataConnectedService.Tests.csproj
- test/ODataConnectedService.Tests/ODataConnectedServiceWizardTests.cs
- test/ODataConnectedService.Tests/ViewModels/OperationImportsViewModelTests.cs
- test/ODataConnectedService.Tests/ViewModels/SchemaTypesViewModelTests.cs
Breaks the UI code from the Async refactor in https://github.com/OData/ODataConnectedService/pull/411 
I added a simple paginator to improve the draw events on the schema page and operation imports page to reduce drawing overhead and increase how responsive the UI is.
The model since it is used severally in the Wizard the results are now cached after transitioning from the ConfigureODataModel page. So moving forward will ensure the UI responds smoothly eliminating IO.
with pagination.
Paginator with filter
> UI fixes to allow smoother transitions between pages and paginate schema items

- azure-pipelines.yml
- src/ODataConnectedService_VS2022Plus/ODataConnectedService_VS2022Plus.csproj
- test.runsettings
Configure code coverage.
Restrict code coverage analysis to libraries being tested:
> Configure test coverage
